### PR TITLE
Update ngModel and solution for keyboard covering input. 

### LINKED ISSUE #31: [ngModel support] Can't read value from textbox which is entered by virtual keyboard.
I have created an app and set Keyboard on a input tag (textbox). Entered value in textbox via virtual keyboard, But control's "dirty" property is not set to true and not even able to read data from textbox. Which is visual but can't be accessed via binding.
Please if this is not an issue, I need to know what am I making wrong here.

Thanks

### PR DESCRIPTION
**Pull request by digaus**
Do not know if this is the best way to handle it but it easy and works.
Fixes #31 / #32

### CODE REVIEW

**Comment by digaus** [comment]
Added better handling if the text in the input is selected (correct override and deletion) Also added the option to display the input with the keyboard hwen you set an inputTitle. This way one can see the input when the keyboard overlays it.

**Comment by shoudaos** [comment]
@davidenke Will you merge this PR?

**Comment by zolee** [comment]
@davidenke Hi. Is it possible to merge this PR?

**Comment by davidenke** [comment]
I'm sorry, this PR covers a lot of things (and maybe also the underlying issue).
But please provide a PR that fixes the issue in question and create new issues for any other kind of fixes or features because it's really difficult to review a PR with +100 lines without any recognizable context.

**Comment by aMedh** [comment]
@digaus do you mind correct your answer like @davidenke suggests? So we can merge it?

"I'm sorry, this PR covers a lot of things (and maybe also the underlying issue).
But please provide a PR that fixes the issue in question and create new issues for any other kind of fixes or features because it's really difficult to review a PR with +100 lines without any recognizable context."

**Comment by digaus** [comment]
Will try when I have the time

**Comment by davidenke** [comment]
The underlying issue has been fixed in 0.1.0.

**Comment by aMedh** [comment]
@davidenke we had to make a local clone and removed following line "this.inputValue = this.control.value;" from esm5/ngx-material-keyboard-core.js to make it work.

**Comment by davidenke** [comment]
Again, the issue should be fixed in 0.1.0.

**Comment by aMedh** [comment]
This time it works indeed. Wierd. I must have done something completely wrong last time. My apologies.

**Comment by RaulGF92** [comment]
I don't know well if @davidenke solved this issue and how can configure the keyboard for can display the cover's inputs under virtual keyboard.

Any can explain me how can use the @davidenke fixes or @digaus solution? Thanks

**Comment by davidenke** [comment]
@RaulGF92 The mentioned issue is fixed since 0.1.0, but the suggested solution for aiding covered inputs targets a different issue. It'll be great if @digaus would update this PR (or create a new one) containing only the feature based on the current master.

**Pull request closed without merging**
