### PR TITLE
Update keyboard-key.component.ts

### PR DESCRIPTION
**Pull request by ydock1**
solved:
 "value.slice is not a function" <- (when the textbox is empty)
 Backspace not working

### CODE REVIEW

**Comment by RANSoftRA** [comment]
tried that fix - works for me.

**Comment by RANSoftRA** [comment]
sry - just figured out that this change only fixes the problem described in #49 - not when the input is prefilled with a number #50

**Comment by RANSoftRA** [comment]
just created a new PR #55 that includes your fixes and also casts the input value to string, so that #50  does not happen.

**Comment by davidenke** [comment]
Closing, since this seams to be part of #55.

**Pull request closed without merging**
